[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "simple-text-mcp-http-server"
version = "0.1.0"
description = "Simple MCP server with Streamable HTTP transport."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "mcp",
    "fastapi",
    "uvicorn"
]


[project.scripts]
simple-text-mcp-http = "server:main"